# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculating the Dissipation of Pixels
#' 
#' @export dissipatePixel
#' @import Rcpp
#' 
#' @keywords internal
#' 
#' @references \insertRef{Hagenburg2009}{Raspository}
#' 
#' @return the image as matrix after the next time step
#'
dissipatePixel <- function(imgOriginal, minimalTreshold) {
    .Call('_Raspository_dissipatePixel', PACKAGE = 'Raspository', imgOriginal, minimalTreshold)
}

