# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculating the Dissipation of Pixels
#' 
#' @export dissipatePixel
#' @import Rcpp
#' 
#' 
#' @references \insertRef{Hagenburg2009}{Raspository}
#' 
#' @return the image as matrix after the next time step
#'
dissipatePixel <- function(imgOriginal, minimalTreshold) {
    .Call('_Raspository_dissipatePixel', PACKAGE = 'Raspository', imgOriginal, minimalTreshold)
}

#' Dither the imge with Floyd Steinberg
#' 
#' @export fsDithering
#' @import Rcpp
#' 
#' 
#' @references \insertRef{Floyd}{Raspository}
#' 
#' @return the image as matrix after dithering
#'
fsDithering <- function(img, transformPaletteFunction) {
    .Call('_Raspository_fsDithering', PACKAGE = 'Raspository', img, transformPaletteFunction)
}

#' Dither the imge with minimized average error
#' 
#' @export meaDithering
#' @import Rcpp
#' 
#' 
#' @references \insertRef{Jarvis1976}{Raspository}
#' 
#' @return the image as matrix after dithering
#'
meaDithering <- function(img, transformPaletteFunction) {
    .Call('_Raspository_meaDithering', PACKAGE = 'Raspository', img, transformPaletteFunction)
}

